# frozen_string_literal: true

class VideoMetadataExtractor
  attr_reader :duration, :bitrate, :video_codec, :audio_codec,
              :colorspace, :width, :height, :display_width, :display_height,
              :frame_rate, :r_frame_rate

  def initialize(path)
    @path     = path
    @metadata = JSON.parse(ffmpeg_command_output, symbolize_names: true)

    parse_metadata
  rescue Terrapin::ExitStatusError, JSON::ParserError
    @invalid = true
  rescue Terrapin::CommandNotFoundError
    raise Paperclip::Errors::CommandNotFoundError, 'Could not run the `ffprobe` command. Please install ffmpeg.' # rubocop:disable I18n/RailsI18n/DecorateString -- This error is not user-facing
  end

  def valid?
    !@invalid
  end

  private

  def ffmpeg_command_output
    command = Terrapin::CommandLine.new(Rails.configuration.x.ffprobe_binary, '-i :path -print_format :format -show_format -show_streams -show_error -loglevel :loglevel')
    command.run(path: @path, format: 'json', loglevel: 'fatal')
  end

  def parse_metadata
    if @metadata.key?(:format)
      @duration = @metadata[:format][:duration].to_f
      @bitrate  = @metadata[:format][:bit_rate].to_i
    end

    if @metadata.key?(:streams)
      video_streams = @metadata[:streams].select { |stream| stream[:codec_type] == 'video' }
      audio_streams = @metadata[:streams].select { |stream| stream[:codec_type] == 'audio' }

      if (video_stream = video_streams.first)
        @video_codec = video_stream[:codec_name]
        @colorspace  = video_stream[:pix_fmt]
        @width       = video_stream[:width]
        @height      = video_stream[:height]
        # Display dimensions correct for non-square pixels (SAR != 1:1) so layout
        # metadata uses the intended display aspect ratio. The coded @width/@height
        # are kept as-is for upload-limit validation and transcoding bitrate (the
        # raster ffmpeg actually decodes), which must not be fooled by the SAR tag.
        sar = parse_sar(video_stream[:sample_aspect_ratio])
        @display_width  = sar && sar != 1 ? (@width * sar).round : @width
        @display_height = @height
        @frame_rate = parse_framerate(video_stream[:avg_frame_rate])
        @r_frame_rate = parse_framerate(video_stream[:r_frame_rate])
        # For some video streams the frame_rate reported by `ffprobe` will be 0/0, but for these streams we
        # should use `r_frame_rate` instead. Video screencast generated by Gnome Screencast have this issue.
        @frame_rate ||= @r_frame_rate
        # If the video has not been re-encoded by ffmpeg, it may contain rotation information,
        # and we need to simulate applying it to the dimensions (coded and display alike)
        if video_stream[:side_data_list]&.any? { |x| x[:rotation]&.abs == 90 }
          @width, @height = @height, @width
          @display_width, @display_height = @display_height, @display_width
        end
      end

      if (audio_stream = audio_streams.first)
        @audio_codec = audio_stream[:codec_name]
      end
    end

    @invalid = true if @metadata.key?(:error)
  end

  def parse_framerate(raw)
    Rational(raw)
  rescue ZeroDivisionError
    nil
  end

  def parse_sar(raw)
    return if raw.nil? || raw == '0:1'

    Rational(raw.tr(':', '/')) # ffprobe reports sample_aspect_ratio as "N:M"
  rescue ZeroDivisionError, ArgumentError
    nil
  end
end
